# Generated by Django 4.2 on 2023-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseHoldNumber', models.IntegerField()),
                ('ResidenceCountry', models.CharField(max_length=65)),
                ('housingSize', models.IntegerField()),
                ('housingType', models.CharField(max_length=65)),
                ('dailyElectricityConsumption', models.IntegerField()),
                ('energySource', models.CharField(max_length=65)),
            ],
        ),
    ]
